name: "Docker Compose Issue"
description: "Report an issue with an existing compose file"
title: "[COMPOSE]: "
labels: ["bug"]
assignees:
  - trentnbauer
body:
  - type: markdown
    attributes:
      value: "Thanks for reporting a bug! Please fill out the sections below."
  - type: textarea
    id: logs
    attributes:
      label: "Compose File"
      description: "Paste the compose file you are using here"
      placeholder: "Don't forget to remove any secret or passwords - I recommend setting them as ${variables}"
      render: json
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Describe the issue"
    validations:
      required: true
  - type: textarea
    id: attempts
    attributes:
      label: "Steps you've taken to try and fix it"
    validations:
      required: false
  - type: textarea
    id: reproduction
    attributes:
      label: "Steps followed / how to reproduce"
      placeholder: "Rebooted host, deleted docker volumes"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Expected Behaviour"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Any relevant log files"
      description: "Paste output from 'docker logs' here."
      render: json
    validations:
      required: false

  # --- Individual Single Line Inputs ---
  - type: input
    id: os
    attributes:
      label: "OS"
      placeholder: "e.g. Ubuntu 24.04, Windows 11"
    validations:
      required: true

  - type: input
    id: docker-version
    attributes:
      label: "Docker Version"
      placeholder: "run command: Docker --version"
    validations:
      required: true

  - type: input
    id: deployment-method
    attributes:
      label: "How Compose is being deployed"
      placeholder: "e.g. Portainer, CLI, DockGE etc"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context"
