name: "Docker Compose Issue"
description: "Create a report to help us improve"
title: "[DC]: "
labels: ["bug"]
assignees:
  - trentnbauer
body:
  - type: markdown
    attributes:
      value: "Thanks for reporting a bug! Please fill out the sections below."
  - type: textarea
    id: description
    attributes:
      label: "Describe the bug"
    validations:
      required: true
  - type: logs
    id: description
    attributes:
      label: "Any relevant log files"
    validations:
      required: false
  - type: textarea
    id: reproduction
    attributes:
      label: "To Reproduce"
    validations:
      required: true

  # --- Individual Single Line Inputs ---
  - type: input
    id: os
    attributes:
      label: "OS"
      placeholder: "e.g. Ubuntu 24.04, Windows 11"
    validations:
      required: true

  - type: input
    id: docker-version
    attributes:
      label: "Docker Version"
      placeholder: "e.g. 27.3.1"
    validations:
      required: true

  - type: input
    id: deployment-method
    attributes:
      label: "How Compose is being deployed"
      placeholder: "e.g. Portainer, CLI, DockGE etc"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context"
