version: '3.8'

services:
  app:
    image: ghcr.io/plexguide/huntarr:9.1.4@sha256:9e08e9ec5718c11a4731dad2ee2e1217c10633e6b8d1af7edad60e5fe57fff58
    networks:
      - cloudflare-net
    restart: always
    ports:
      - ${PORT:-9705}:9705
    volumes:
      - config:/config
    environment:
      - TZ=${TZ:-Australia/Melbourne}
      - BASE_URL=${CFURLPATH:-}
    healthcheck:
      test: netstat -ltn | grep -c ":9705"
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - autoheal=true
      - dfgeneric.enable=${CFTUNNEL:-true}
      - dfgeneric.0.hostname=${CFSUBDOMAIN}${CFDOMAIN}
      - dfgeneric.0.service=http://${HOSTNAME:-localhost}:${PORT:-9705}
      - dfgeneric.0.access.policy=${CFPOLICY:-default_tld}
      - dfgeneric.0.zonename=${CFDOMAIN}
      - dfgeneric.0.path=${CFURLPATH:-}
volumes:
  config:
networks:
    cloudflare-net:
        name: cloudflare-net
        external: true

