version: '3.8'

services:
  app:
    image: ghcr.io/plexguide/huntarr:9.3.7@sha256:95e88b2595f71b1ec2e158a3b9461c573e192928c51ac2b0d9675f33d4cdba15
    networks:
      - cloudflare-net
    restart: always
    ports:
      - ${PORT:-9705}:9705
    volumes:
      - config:/config
    environment:
      - TZ=${TZ:-Australia/Melbourne}
      - BASE_URL=${CFURLPATH:-}
    healthcheck:
      test: netstat -ltn | grep -c ":9705"
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - autoheal=true
      - dfgeneric.enable=${CFTUNNEL:-true}
      - dfgeneric.0.hostname=${CFSUBDOMAIN}${CFDOMAIN}
      - dfgeneric.0.service=http://${HOSTNAME:-localhost}:${PORT:-9705}
      - dfgeneric.0.access.policy=${CFPOLICY:-default_tld}
      - dfgeneric.0.zonename=${CFDOMAIN}
      - dfgeneric.0.path=${CFURLPATH:-}
volumes:
  config:
networks:
    cloudflare-net:
        name: cloudflare-net
        external: true

