version: '3'
services:
  app:
    image: ghcr.io/linuxserver/overseerr:1.34.0@sha256:b21e06654f321a94778ea314f693a4b1c073d99ef36881c7f493e2afc6c08b20
    environment:
      - TZ=${TZ:-Australia/Melbourne}
    volumes:
      - app:/config
      #- www:/app/overseerr/public #rebrand overseerr https://github.com/sct/overseerr/issues/404#issuecomment-1659795118
    ports:
      - ${WEBPORT:-5055}:5055
    restart: unless-stopped
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail http://localhost:5055/api/v1/status
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 30s
    labels:
      - autoheal=true
      - dfgeneric.enable=true
      - dfgeneric.hostname=${SUBDOMAIN}${DOMAIN}
      - dfgeneric.service=http://${HOSTNAME:-localhost}:${WEBPORT:-5055}
      - dfgeneric.access.policy=${CFPOLICY:-bypass}
      - dfgeneric.name=${CFACCESSNAME:-Overseerr}
      - dfgeneric.zonename=${DOMAIN}
      - dfgeneric.path=${URLPATH:-}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"      
volumes:
  app:
  #www:






