version: '3'
services:
  app:
    image: ghcr.io/linuxserver/overseerr:1.34.0@sha256:f6a782e44742a02bdb6032d32ebb4e9615e261140f879be897b28cdb40ff800e
    environment:
      - TZ=${TZ:-Australia/Melbourne}
    volumes:
      - app:/config
      #- www:/app/overseerr/public #rebrand overseerr https://github.com/sct/overseerr/issues/404#issuecomment-1659795118
    ports:
      - ${WEBPORT:-5055}:5055
    restart: unless-stopped
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail http://localhost:5055/api/v1/status
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 30s
    labels:
      - autoheal=true
      - dockflare.0.access.enable=true
      - dockflare.0.access.hostname=${SUBDOMAIN}${DOMAIN}
      - dockflare.0.access.service=http://${HOSTNAME:-localhost}:${WEBPORT:-5055}
      - dockflare.0.access.access.policy=${CFPOLICY:-authenticate}
      - dockflare.0.access.name=${CFACCESSNAME:-Overseerr}
      - dockflare.0.access.zonename=${DOMAIN}
      - dockflare.0.access.path=${URLPATH:-}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"      
volumes:
  app:
  #www:



