---
version: "2.1"
services:
  app:
    image: ghcr.io/linuxserver/prowlarr:2.3.0@sha256:d3e9307b320b6772749a2cf8fc2712e9e824c4930b034680ad4d08a9e2f25884
    networks:
      - cloudflare-net
    environment:
      #- PUID=1000
      #- PGID=1000
      - TZ=$TZ
    volumes:
      - config:/config
      - media:/media
      - downloads:/downloads
    ports:
      - ${PORT:-9696}:9696
    restart: unless-stopped
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail -k http://localhost:9696
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - autoheal=true
      - dfgeneric.enable=${CFTUNNEL:-true}
      - dfgeneric.0.hostname=${CFSUBDOMAIN}${CFDOMAIN}
      - dfgeneric.0.service=http://${HOSTNAME:-localhost}:${PORT:-9696}
      - dfgeneric.0.access.policy=${CFPOLICY:-default_tld}
      - dfgeneric.0.zonename=${CFDOMAIN}
      - dfgeneric.0.path=${CFURLPATH:-}
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
volumes:
  config:
  media:
    driver_opts:
      type: nfs
      o: addr=$STORAGE,nfsvers=4
      device: :$MEDIA
  downloads:
    driver_opts:
      type: nfs 
      o: addr=$STORAGE,nfsvers=4
      device: :$DOWNLOAD

networks:
  cloudflare-net:
    name: cloudflare-net
    external: true

