---
version: "2.3"
services:
  app:
    image: ghcr.io/linuxserver/radarr:6.0.4@sha256:ba2693dd704b84eb0b404d40b3902bd3e62a1768dc5ee0d89b1f1d7cd51a66eb
    hostname: ${ALIAS:-radarr}
    networks:
      - cloudflare-net
    environment:
      #- PUID=1000
      #- PGID=1000
      - TZ=$TZ
    volumes:
      - config:/config
      - media:/movies
      - downloads:/downloads
    ports:
      - ${PORT:-7878}:7878
    restart: unless-stopped
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail -k http://localhost:7878/ping
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - autoheal=true
      - dfgeneric.enable=${CFTUNNEL:-true}
      - dfgeneric.0.hostname=${CFSUBDOMAIN}${CFDOMAIN}
      - dfgeneric.0.service=http://${HOSTNAME:-localhost}:${PORT:-5055}
      - dfgeneric.0.access.policy=${CFPOLICY:-default_tld}
      - dfgeneric.0.zonename=${CFDOMAIN}
      - dfgeneric.0.path=${CFURLPATH:-}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  config:
  media:
    driver_opts:
      type: nfs
      o: addr=$STORAGE,nfsvers=4
      device: :$MEDIA
  downloads:
    driver_opts:
      type: nfs 
      o: addr=$STORAGE,nfsvers=4
      device: :$DOWNLOAD
networks:
  cloudflare-net:
    name: cloudflare-net
    external: true

