---
version: "2.3"
services:
  app:
    image: ghcr.io/linuxserver/sonarr:4.0.16@sha256:02b4d538d351d6e35882a021c08e8600fe95d28860fb1dd724b597166e7221ca
    environment:
      #- PUID=1000
      #- PGID=1000
      - TZ=$TZ
    volumes:
      - config:/config
      - media:/tv #optional
      - downloads:/downloads
    networks:
      - cloudflare-net
    ports:
      - ${PORT:-8989}:8989
    restart: unless-stopped
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail http://localhost:8989/ping
      interval: 3m
      timeout: 30s
      retries: 3
      start_period: 30s
    labels:
      - autoheal=true
      - dfgeneric.enable=${CFTUNNEL:-true}
      - dfgeneric.0.hostname=${CFSUBDOMAIN}${CFDOMAIN}
      - dfgeneric.0.service=http://${HOSTNAME:-localhost}:${PORT:-8989}
      - dfgeneric.0.access.policy=${CFPOLICY:-default_tld}
      - dfgeneric.0.zonename=${CFDOMAIN}
      - dfgeneric.0.path=${CFURLPATH:-}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  config:
  media:
    driver_opts:
      type: nfs
      o: addr=$STORAGE,nfsvers=4
      device: :$MEDIA
  downloads:
    driver_opts:
      type: nfs 
      o: addr=$STORAGE,nfsvers=4
      device: :$DOWNLOAD

networks:
  cloudflare-net:
    name: cloudflare-net
    external: true

