version: "2.3"
services:
  server:
    image: ghcr.io/haveagitgat/tdarr:2.58.02
    restart: unless-stopped
    ports:
      - ${WEBUI:-8265}:8265 # webUI port
      - ${SERVER:-8266}:${SERVER:-8266} # server port
      - 8267:8267
    environment:
      - TZ=${TZ:-Australia/Melbourne}
      #- PUID=${PUID}
      #- PGID=${PGID}
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=${SERVER:-8266}
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=${FFMPEGVER:-6}
      - nodeName=${SERVNAME:-Server}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - server:/app/server
      - configs:/app/configs
      - logs:/app/logs
      - media:/media
      - /cache:/temp
      - /etc/hostname:/etc/hostname:ro
    devices:
      - /dev/dri:/dev/dri
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8265/"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - autoheal=true
      - dockflare.enable=${CFTUNNEL:-true}
      - dockflare.0.hostname=${CFSUBDOMAIN}${CFDOMAIN}
      - dockflare.0.service=http://${HOSTNAME:-localhost}:${WEBUI:-8265}
      - dockflare.0.access.policy=${CFPOLICY:-default_tld}
      - dockflare.0.zonename=${CFDOMAIN}
      - dockflare.0.path=${CFURLPATH:-}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 
    deploy:
      restart_policy:
        condition: on-failure
        delay: 90s
        max_attempts: 3
        window: 120s
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
            
  nodeA:
    image: ghcr.io/haveagitgat/tdarr_node:2.58.02
    restart: unless-stopped
    network_mode: service:server
    environment:
      - TZ=${TZ:-Australia/Melbourne}
      #- PUID=${PUID}
      #- PGID=${PGID}
      - UMASK_SET=002
      - nodeName=${NODENAME:-}NodeA
      - serverIP=0.0.0.0
      - serverPort=${SERVERPORT:-8266}
      - inContainer=true
      - ffmpegVersion=${FFMPEGVER:-6}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - configs:/app/configs
      - logs:/app/logs
      - media:/media
      - /cache:/temp
      - /etc/hostname:/etc/hostname:ro
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8265/"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 60s
    devices:
      - /dev/dri:/dev/dri
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 
    deploy:
      restart_policy:
        condition: on-failure
        delay: 90s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: ${CPULIMIT:-2}
          memory: ${RAMLIMIT:-2G}
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
volumes:
  server:
  configs:
  logs:
  media:
    driver_opts:
      type: "nfs"
      o: addr=$MEDIASERV,nfsvers=4
      device: $MEDIAPATH
