version: '3.3'

services:
  app:
    image: ghcr.io/louislam/uptime-kuma:2.1.1@sha256:e4045dc9b2b96a5503be7372e3b648104ba7153e452974c2247c66178389ac39
    volumes:
      - app:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=true
      - UPTIME_KUMA_WS_ORIGIN_CHECK=bypass
      - UPTIME_KUMA_CLOUDFLARED_TOKEN=$CFTOKEN
    ports:
      - ${PORT:-3001}:3001  # <Host Port>:<Container Port>
    restart: always
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail -k http://LOCALHOST:3001
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - autoheal=true
      - dfgeneric.enable=${CFTUNNEL:-true}
      - dfgeneric.0.hostname=${CFSUBDOMAIN0}${CFDOMAIN0}
      - dfgeneric.0.service=http://${HOSTNAME:-localhost}:${PORT:-3001}
      - dfgeneric.0.access.policy=${CFPOLICY0:-default_tld}
      - dfgeneric.0.zonename=${CFDOMAIN0}
      - dfgeneric.0.path=${CFURLPATH0:-}

      - dfgeneric.1.hostname=${CFSUBDOMAIN1}${CFDOMAIN1}
      - dfgeneric.1.service=http://${HOSTNAME:-localhost}:${PORT:-3001}
      - dfgeneric.1.access.policy=${CFPOLICY1:-default_tld}
      - dfgeneric.1.zonename=${CFDOMAIN1}
      - dfgeneric.1.path=${CFURLPATH1:-}

      - dfgeneric.2.hostname=${CFSUBDOMAIN2}${CFDOMAIN2}
      - dfgeneric.2.service=http://${HOSTNAME:-localhost}:${PORT:-3001}
      - dfgeneric.2.access.policy=${CFPOLICY2:-default_tld}
      - dfgeneric.2.zonename=${CFDOMAIN2}
      - dfgeneric.2.path=${CFURLPATH2:-}

      - dfgeneric.3.hostname=${CFSUBDOMAIN3}${CFDOMAIN3}
      - dfgeneric.3.service=http://${HOSTNAME:-localhost}:${PORT:-3001}
      - dfgeneric.3.access.policy=${CFPOLICY3:-default_tld}
      - dfgeneric.3.zonename=${CFDOMAIN3}
      - dfgeneric.3.path=${CFURLPATH3:-}

      - dfgeneric.4.hostname=${CFSUBDOMAIN4}${CFDOMAIN4}
      - dfgeneric.4.service=http://${HOSTNAME:-localhost}:${PORT:-3001}
      - dfgeneric.4.access.policy=${CFPOLICY4:-default_tld}
      - dfgeneric.4.zonename=${CFDOMAIN4}
      - dfgeneric.4.path=${CFURLPATH4:-}

      - dfgeneric.5.hostname=${CFSUBDOMAIN5}${CFDOMAIN5}
      - dfgeneric.5.service=http://${HOSTNAME:-localhost}:${PORT:-3001}
      - dfgeneric.5.access.policy=${CFPOLICY5:-default_tld}
      - dfgeneric.5.zonename=${CFDOMAIN5}
      - dfgeneric.5.path=${CFURLPATH5:-}

      - dfgeneric.6.hostname=${CFSUBDOMAIN6}${CFDOMAIN6}
      - dfgeneric.6.service=http://${HOSTNAME:-localhost}:${PORT:-3001}
      - dfgeneric.6.access.policy=${CFPOLICY6:-default_tld}
      - dfgeneric.6.zonename=${CFDOMAIN6}
      - dfgeneric.6.path=${CFURLPATH6:-}
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
volumes:
  app:

