---
version: "3.5"
services:
  app:
    image: ghcr.io/wizarrrr/wizarr:2025.9.1@sha256:b3bf6d81a59d0d1b0fef7cb757b529012173ea084e865310e045508f4b33c2a7
    ports:
      - ${PORT:-5690}:5690
    volumes:
      - db:/data/database
      - steps:/data/wizard_steps
    restart: unless-stopped
    labels:
      - autoheal=true
      - dfgeneric.enable=${CFTUNNEL:-true}
      ### PUBLIC UI
      - dfgeneric.0.hostname=${CFSUBDOMAIN}${CFDOMAIN}
      - dfgeneric.0.service=http://${HOSTNAME:-localhost}:${PORT:-5690}
      - dfgeneric.0.access.policy=bypass
      - dfgeneric.0.name=Wizarr Public
      - dfgeneric.0.zonename=${CFDOMAIN}
      - dfgeneric.0.path=${CFURLPATH:-}/j
      ### ADMIN UI
      - dfgeneric.1.hostname=${CFSUBDOMAIN}${CFDOMAIN}
      - dfgeneric.1.service=http://${HOSTNAME:-localhost}:${PORT:-5690}
      - dfgeneric.1.access.policy=${CFPOLICY:-default_tld}
      - dfgeneric.1.name=Wizarr Admin
      - dfgeneric.1.zonename=${CFDOMAIN}
      - dfgeneric.1.path=${CFURLPATH:-}/login ## Secure the Admin side of the app
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail -k http://localhost:5690
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
        - TZ=${TZ:-Australia/Melbourne}
        - DISABLE_BUILTIN_AUTH=${DISABLEAUTH:-true}
volumes:
  db:
  steps:

