name: Approve & Merge

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'trentnbauer'
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          review-message: "PR created by Trent - auto approved"
  auto-merge:
    runs-on: ubuntu-latest
    needs: auto-approve
    permissions:
      pull-requests: write
      contents: write
    if: github.actor == 'trentnbauer'
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GH_PAT }}"
          MERGE_METHOD: "squash"
          MERGE_LABELS: ""
          MERGE_RETRIES: "10"
          MERGE_RETRY_SLEEP: "10000"
